language: node_js
node_js: "6"

os:
  - linux
  - osx

sudo: false

git:
  depth: 10

branches:
  only:
    - master

env:
  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
